name: exercise_11
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.3.5
  - pip=22.3.1
  - scikit-learn=0.24.1
  - matplotlib==3.6.2
  - plotly==5.12.0
  - pillow=9.4.0
  - pip:
      - wandb==0.13.7
      - omegaconf==2.3.0