name: exercise_3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=22.3.1
  - requests=2.28.1
  - mlflow=2.0.1
  - hydra-core=1.3.1
  - omegaconf=2.3.0
  - pip:
      - wandb==0.13.7