name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.28.1
  - pip=22.3.1
  - seaborn=0.12.2
  - pandas=1.3.5
  - scikit-learn=1.2.0
  - matplotlib==3.6.2
  - pillow=9.4.0
  - pip:
      - wandb==0.13.7
