name: exercise_4
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - seaborn=0.12.2
  - pandas=1.3.5
  - pip=22.3.1
  - pandas-profiling=3.6.2
  - pyarrow=10.0.1
  - pip:
      - wandb==0.13.7